// Fichier : produits/accessoires.js
// 50 accessoires pour téléphones (iPhone, Samsung, etc.)

function getProduitsAccessoires() {
    return [
        // 1-10 : Câbles et chargeurs
        { id: 200, nom: "Câble USB-C vers Lightning 1m", prix: 6, description: "Câble certifié MFi, charge rapide et synchronisation.", image: "https://via.placeholder.com/300x200?text=Cable+Lightning+1m", specs: { longueur: "1 mètre", connectique: "USB-C à Lightning", certification: "MFi", charge: "Jusqu'à 20W" }, note: 4.5, avis: 150, en_stock: true },
        { id: 201, nom: "Câble USB-C vers Lightning 2m", prix: 8, description: "Version 2 mètres, idéal pour une utilisation à distance.", image: "https://via.placeholder.com/300x200?text=Cable+Lightning+2m", specs: { longueur: "2 mètres", connectique: "USB-C à Lightning", certification: "MFi", charge: "Jusqu'à 20W" }, note: 4.6, avis: 220, en_stock: true },
        { id: 202, nom: "Câble USB-C vers USB-C 1m", prix: 5, description: "Câble rapide pour chargeur et données, compatible tous appareils USB-C.", image: "https://via.placeholder.com/300x200?text=Cable+USB-C+1m", specs: { longueur: "1 mètre", connectique: "USB-C à USB-C", débit: "480 Mbps", puissance: "60W" }, note: 4.4, avis: 95, en_stock: true },
        { id: 203, nom: "Câble USB-C vers USB-C 2m", prix: 7, description: "Câble robuste tressé, transfert rapide et charge jusqu'à 100W.", image: "https://via.placeholder.com/300x200?text=Cable+USB-C+2m", specs: { longueur: "2 mètres", connectique: "USB-C à USB-C", débit: "10 Gbps", puissance: "100W" }, note: 4.7, avis: 180, en_stock: true },
        { id: 204, nom: "Câble USB-A vers Lightning 1m", prix: 5, description: "Câble classique pour anciens chargeurs, certifié MFi.", image: "https://via.placeholder.com/300x200?text=Cable+USB-A+Lightning", specs: { longueur: "1 mètre", connectique: "USB-A à Lightning", certification: "MFi", charge: "12W" }, note: 4.3, avis: 300, en_stock: true },
        { id: 205, nom: "Câble USB-A vers Micro-USB 1m", prix: 3, description: "Pour anciens téléphones et accessoires, fiable.", image: "https://via.placeholder.com/300x200?text=Cable+Micro-USB", specs: { longueur: "1 mètre", connectique: "USB-A à Micro-USB", charge: "10W" }, note: 4.2, avis: 120, en_stock: true },
        { id: 206, nom: "Chargeur secteur 20W USB-C", prix: 12, description: "Charge rapide pour iPhone et Samsung, compact et sûr.", image: "https://via.placeholder.com/300x200?text=Chargeur+20W", specs: { type: "USB-C", puissance: "20W", compatibilité: "Universelle", protection: "Surtension, surchauffe" }, note: 4.6, avis: 410, en_stock: true },
        { id: 207, nom: "Chargeur secteur 30W USB-C", prix: 15, description: "Charge rapide pour iPad, iPhone et téléphones compatibles.", image: "https://via.placeholder.com/300x200?text=Chargeur+30W", specs: { type: "USB-C", puissance: "30W", compatibilité: "iPhone, iPad, Samsung", charge rapide: "PD 3.0" }, note: 4.7, avis: 230, en_stock: true },
        { id: 208, nom: "Chargeur secteur 65W GaN", prix: 25, description: "Chargeur compact pour ordinateur et téléphone, double port.", image: "https://via.placeholder.com/300x200?text=Chargeur+65W", specs: { type: "GaN", ports: "2x USB-C", puissance: "65W", compatibilité: "Ordinateur, téléphone" }, note: 4.8, avis: 150, en_stock: true },
        { id: 209, nom: "Chargeur allume-cigare 30W", prix: 10, description: "Charge rapide en voiture, deux ports USB.", image: "https://via.placeholder.com/300x200?text=Chargeur+Voiture", specs: { ports: "1x USB-C, 1x USB-A", puissance: "30W", tension: "12-24V" }, note: 4.5, avis: 85, en_stock: true },

        // 11-20 : Batteries externes
        { id: 210, nom: "Power Bank 5000 mAh", prix: 12, description: "Petite batterie nomade, format poche, charge rapide.", image: "https://via.placeholder.com/300x200?text=Power+Bank+5000", specs: { capacité: "5000 mAh", ports: "1x USB-A, 1x Micro-USB", poids: "120g", charge: "10W" }, note: 4.4, avis: 60, en_stock: true },
        { id: 211, nom: "Power Bank 10000 mAh", prix: 18, description: "Batterie externe 10000 mAh, deux ports, charge rapide.", image: "https://via.placeholder.com/300x200?text=Power+Bank+10000", specs: { capacité: "10000 mAh", ports: "2x USB-A, 1x USB-C", technologie: "Li-Po", charge rapide: "18W" }, note: 4.6, avis: 210, en_stock: true },
        { id: 212, nom: "Power Bank 20000 mAh", prix: 25, description: "Grande capacité pour plusieurs recharges, compatible avion.", image: "https://via.placeholder.com/300x200?text=Power+Bank+20000", specs: { capacité: "20000 mAh", ports: "2x USB-A, 1x USB-C, 1x Micro-USB", charge rapide: "22.5W" }, note: 4.7, avis: 190, en_stock: true },
        { id: 213, nom: "Power Bank sans fil 10000 mAh", prix: 22, description: "Charge sans fil intégrée, plus câble pour charge filaire.", image: "https://via.placeholder.com/300x200?text=Power+Bank+Wireless", specs: { capacité: "10000 mAh", charge sans fil: "10W", ports: "1x USB-C, 1x USB-A" }, note: 4.5, avis: 80, en_stock: true },
        { id: 214, nom: "Station d'accueil chargeur sans fil 3-en-1", prix: 30, description: "Charge simultanée iPhone, Apple Watch, AirPods.", image: "https://via.placeholder.com/300x200?text=Chargeur+3-en-1", specs: { type: "Induction", puissance: "15W max", compatibilité: "iPhone, Watch, AirPods" }, note: 4.8, avis: 120, en_stock: true },

        // 21-30 : Coques et protections
        { id: 215, nom: "Coque silicone iPhone 15", prix: 8, description: "Coque officielle en silicone, protection légère, couleur au choix.", image: "https://via.placeholder.com/300x200?text=Coque+iPhone+15", specs: { matière: "Silicone", compatible: "iPhone 15", couleur: "Multiple", finition: "Soft touch" }, note: 4.5, avis: 210, en_stock: true },
        { id: 216, nom: "Coque silicone iPhone 14", prix: 8, description: "Coque souple et élégante pour iPhone 14.", image: "https://via.placeholder.com/300x200?text=Coque+iPhone+14", specs: { matière: "Silicone", compatible: "iPhone 14", couleur: "Multiple", finition: "Soft touch" }, note: 4.4, avis: 180, en_stock: true },
        { id: 217, nom: "Coque cuir iPhone 15 Pro", prix: 15, description: "Coque en cuir véritable, aspect premium et protection.", image: "https://via.placeholder.com/300x200?text=Coque+Cuir+iPhone+15", specs: { matière: "Cuir", compatible: "iPhone 15 Pro", couleur: "Noir, Brun" }, note: 4.7, avis: 90, en_stock: true },
        { id: 218, nom: "Coque transparente anti-jaunissement", prix: 5, description: "Coque ultra fine, résiste au jaunissement.", image: "https://via.placeholder.com/300x200?text=Coque+Transparente", specs: { matière: "TPU + PC", compatible: "iPhone 13/14/15", épaisseur: "1mm" }, note: 4.3, avis: 320, en_stock: true },
        { id: 219, nom: "Coque avec anneau rotatif", prix: 7, description: "Coque avec anneau pour meilleure prise et support.", image: "https://via.placeholder.com/300x200?text=Coque+Anneau", specs: { matière: "TPU", compatible: "Universel", anneau: "360° rotatif" }, note: 4.4, avis: 110, en_stock: true },
        { id: 220, nom: "Coque étanche iPhone", prix: 20, description: "Protection contre l'eau et la poussière, immersion jusqu'à 2m.", image: "https://via.placeholder.com/300x200?text=Coque+Etanche", specs: { norme: "IP68", compatible: "iPhone 13/14/15", utilisation: "Plage, piscine" }, note: 4.6, avis: 65, en_stock: true },
        { id: 221, nom: "Coque Samsung Galaxy S24 Ultra", prix: 10, description: "Coque rigide avec protection renforcée.", image: "https://via.placeholder.com/300x200?text=Coque+S24+Ultra", specs: { matière: "Polycarbonate", compatible: "Galaxy S24 Ultra", couleur: "Noir" }, note: 4.5, avis: 70, en_stock: true },
        { id: 222, nom: "Coque Samsung Galaxy A54", prix: 8, description: "Coque flexible et fine pour Galaxy A54.", image: "https://via.placeholder.com/300x200?text=Coque+A54", specs: { matière: "TPU", compatible: "Galaxy A54", couleur: "Multiple" }, note: 4.3, avis: 55, en_stock: true },
        { id: 223, nom: "Verre trempé 9H iPhone 15", prix: 4, description: "Protection d'écran en verre trempé, installation facile.", image: "https://via.placeholder.com/300x200?text=Verre+Trempe+iPhone", specs: { dureté: "9H", épaisseur: "0.33mm", application: "Sans bulle", compatible: "iPhone 15" }, note: 4.5, avis: 430, en_stock: true },
        { id: 224, nom: "Verre trempé Samsung S24 Ultra", prix: 5, description: "Verre trempé haute transparence pour S24 Ultra.", image: "https://via.placeholder.com/300x200?text=Verre+Trempe+S24", specs: { dureté: "9H", épaisseur: "0.3mm", compatible: "S24 Ultra", revêtement: "Oléophobe" }, note: 4.6, avis: 120, en_stock: true },
        { id: 225, nom: "Film hydrogel protection", prix: 3, description: "Film souple auto-cicatrisant, protection contre les rayures.", image: "https://via.placeholder.com/300x200?text=Film+Hydrogel", specs: { matière: "TPU", épaisseur: "0.15mm", application: "Humide", compatible: "Universel" }, note: 4.2, avis: 200, en_stock: true },

        // 31-40 : Audio
        { id: 226, nom: "Écouteurs filaires Lightning", prix: 8, description: "Écouteurs avec connecteur Lightning, télécommande et micro.", image: "https://via.placeholder.com/300x200?text=Ecouteurs+Lightning", specs: { connectique: "Lightning", micro: "Oui", commande: "Volume, lecture" }, note: 4.3, avis: 150, en_stock: true },
        { id: 227, nom: "Écouteurs filaires USB-C", prix: 7, description: "Écouteurs numériques USB-C, compatibles Pixel, Samsung.", image: "https://via.placeholder.com/300x200?text=Ecouteurs+USB-C", specs: { connectique: "USB-C", micro: "Oui", compatibilité: "Android, PC" }, note: 4.2, avis: 95, en_stock: true },
        { id: 228, nom: "Écouteurs Bluetooth 5.3 TWS", prix: 18, description: "Écouteurs sans fil avec étui de charge, autonomie 24h.", image: "https://via.placeholder.com/300x200?text=Ecouteurs+TWS", specs: { Bluetooth: "5.3", autonomie: "6h + 18h (étui)", charge: "USB-C", latence: "Faible" }, note: 4.5, avis: 300, en_stock: true },
        { id: 229, nom: "Casque Bluetooth supra-auriculaire", prix: 30, description: "Casque confortable, réduction passive du bruit, autonomie 20h.", image: "https://via.placeholder.com/300x200?text=Casque+Bluetooth", specs: { type: "Supra-auriculaire", autonomie: "20h", Bluetooth: "5.0", pliable: "Oui" }, note: 4.4, avis: 80, en_stock: true },
        { id: 230, nom: "Casque à réduction de bruit ANC", prix: 55, description: "Casque avec suppression active du bruit, son haute qualité.", image: "https://via.placeholder.com/300x200?text=Casque+ANC", specs: { réduction: "Active", autonomie: "30h", Bluetooth: "5.2", charge rapide: "Oui" }, note: 4.8, avis: 110, en_stock: true },
        { id: 231, nom: "Adaptateur Lightning vers jack 3.5mm", prix: 5, description: "Permet de brancher des écouteurs filaires classiques sur iPhone.", image: "https://via.placeholder.com/300x200?text=Adaptateur+Lightning", specs: { entrée: "Lightning", sortie: "Jack 3.5mm", DAC: "Intégré" }, note: 4.5, avis: 210, en_stock: true },
        { id: 232, nom: "Adaptateur USB-C vers jack 3.5mm", prix: 4, description: "Pour téléphones Android et PC sans prise jack.", image: "https://via.placeholder.com/300x200?text=Adaptateur+USB-C+Jack", specs: { entrée: "USB-C", sortie: "Jack 3.5mm", support: "DAC" }, note: 4.3, avis: 140, en_stock: true },

        // 41-50 : Supports, montres, divers
        { id: 233, nom: "Support voiture magnétique", prix: 9, description: "Fixation aimantée pour tableau de bord ou grille d'aération.", image: "https://via.placeholder.com/300x200?text=Support+Voiture", specs: { fixation: "Aimant + ventouse", rotation: "360°", compatibilité: "Tous smartphones" }, note: 4.4, avis: 260, en_stock: true },
        { id: 234, nom: "Support vélo pour smartphone", prix: 12, description: "Support robuste pour guidon de vélo, rotation 360°.", image: "https://via.placeholder.com/300x200?text=Support+Velo", specs: { fixation: "Guidon", rotation: "360°", matériau: "Plastique renforcé" }, note: 4.5, avis: 70, en_stock: true },
        { id: 235, nom: "Support de bureau réglable", prix: 10, description: "Support en aluminium, pliable, pour regarder des vidéos confortablement.", image: "https://via.placeholder.com/300x200?text=Support+Bureau", specs: { matière: "Aluminium", pliable: "Oui", réglable: "2 angles" }, note: 4.6, avis: 180, en_stock: true },
        { id: 236, nom: "Anneau magnétique PopSocket", prix: 4, description: "Anneau aimanté pour meilleure prise, compatible MagSafe.", image: "https://via.placeholder.com/300x200?text=Anneau+MagSafe", specs: { type: "Aimant", usage: "Prise en main, support", couleur: "Multiple" }, note: 4.3, avis: 90, en_stock: true },
        { id: 237, nom: "Montre connectée GT3", prix: 45, description: "Montre sportive, fréquence cardiaque, GPS, notifications.", image: "https://via.placeholder.com/300x200?text=Montre+GT3", specs: { écran: "1.75 pouces AMOLED", batterie: "10 jours", étanchéité: "5 ATM", compatibilité: "iOS, Android" }, note: 4.5, avis: 130, en_stock: true },
        { id: 238, nom: "Bracelet connecté Mi Band 8", prix: 30, description: "Tracker d'activité, suivi du sommeil, autonomie 14 jours.", image: "https://via.placeholder.com/300x200?text=Mi+Band+8", specs: { écran: "AMOLED", autonomie: "14 jours", étanchéité: "5 ATM", capteurs: "FC, SpO2" }, note: 4.6, avis: 200, en_stock: true },
        { id: 239, nom: "Adaptateur secteur multiport 4 USB", prix: 15, description: "Chargeur de voyage avec 4 ports USB, charge simultanée.", image: "https://via.placeholder.com/300x200?text=Chargeur+4+ports", specs: { ports: "4x USB-A", puissance: "30W total", protection: "Oui" }, note: 4.4, avis: 110, en_stock: true },
        { id: 240, nom: "Station de charge pour montres", prix: 20, description: "Chargeur pour Apple Watch / Samsung Watch, câble intégré.", image: "https://via.placeholder.com/300x200?text=Chargeur+Watch", specs: { type: "Induction", compatibilité: "Apple Watch, Samsung Watch", câble: "USB-C" }, note: 4.5, avis: 60, en_stock: true },
        { id: 241, nom: "Nettoyant pour écran 100ml", prix: 3, description: "Spray nettoyant non abrasif, microfibre incluse.", image: "https://via.placeholder.com/300x200?text=Nettoyant+Ecran", specs: { volume: "100ml", contenu: "Liquide + chiffon", utilisation: "Écrans, lunettes" }, note: 4.2, avis: 50, en_stock: true },
        { id: 242, nom: "Grip One Hand", prix: 2, description: "Petit anneau adhésif pour maintenir le téléphone à l'arrière.", image: "https://via.placeholder.com/300x200?text=Grip", specs: { couleur: "Noir, Blanc", adhésif: "Fort" }, note: 4.1, avis: 30, en_stock: true },
        { id: 243, nom: "Sacoche étanche pour téléphone", prix: 8, description: "Pochette étanche pour protéger à la plage ou piscine.", image: "https://via.placeholder.com/300x200?text=Sacoche+Etanche", specs: { matière: "PVC", étanchéité: "IPX8", taille: "jusqu'à 6.7 pouces" }, note: 4.3, avis: 45, en_stock: true },
        { id: 244, nom: "Lunettes VR 3D pour smartphone", prix: 12, description: "Casque VR universel, visionnage de vidéos immersives.", image: "https://via.placeholder.com/300x200?text=Lunettes+VR", specs: { compatibilité: "4.7-6.5 pouces", réglage: "Interpupillaire", matériau: "Plastique ABS" }, note: 4.2, avis: 40, en_stock: true },
        { id: 245, nom: "Carte SIM vers Nano-SIM découpeur", prix: 3, description: "Outil pour découper une carte SIM standard en nano.", image: "https://via.placeholder.com/300x200?text=Decoupeur+SIM", specs: { type: "Découpeur + adaptateur", matériau: "Métal" }, note: 4.0, avis: 25, en_stock: true },
        { id: 246, nom: "Kit d'outils pour réparation", prix: 6, description: "Tournevis, leviers, ventouse pour ouvrir téléphones.", image: "https://via.placeholder.com/300x200?text=Kit+Reparation", specs: { pièces: "12 pièces", usage: "Smartphone, tablette" }, note: 4.4, avis: 80, en_stock: true },
        { id: 247, nom: "Adaptateur USB-C vers HDMI", prix: 10, description: "Permet de connecter le téléphone à un écran ou TV.", image: "https://via.placeholder.com/300x200?text=Adaptateur+HDMI", specs: { entrée: "USB-C", sortie: "HDMI", résolution: "4K@30Hz" }, note: 4.5, avis: 70, en_stock: true },
        { id: 248, nom: "Clé USB OTG 64GB", prix: 12, description: "Clé USB avec connecteur USB-C et USB-A pour transfert facile.", image: "https://via.placeholder.com/300x200?text=Cle+USB+OTG", specs: { capacité: "64 Go", connecteurs: "USB-C, USB-A", vitesse: "Lecture 100 Mo/s" }, note: 4.5, avis: 90, en_stock: true },
        { id: 249, nom: "Mini ventilateur USB", prix: 5, description: "Petit ventilateur portable à brancher sur power bank ou ordinateur.", image: "https://via.placeholder.com/300x200?text=Mini+Ventilateur", specs: { alimentation: "USB", vitesse: "2 vitesses", flexible: "Oui" }, note: 4.1, avis: 35, en_stock: true }
    ];
                                                                                                                                                                                                                                }
